FactoryGirl.define do
  factory :story do
    name_1 "MyString"
    verb_1 "MyString"
    adj_1 "MyString"
    adv_1 "MyString"
    fam "MyString"
    name_2 "MyString"
    number "MyString"
    verb_2 "MyString"
    noun_1 "MyString"
    mil_rank "MyString"
    adj_2 "MyString"
    adj_3 "MyString"
    adj_4 "MyString"
    noun_2 "MyString"
    award "MyString"
    adj_5 "MyString"
    name_3 "MyString"
    verb_3 "MyString"
    noun_3 "MyString"
    verb_4 "MyString"
    adj_6 "MyString"
    verb_5 "MyString"
    verb_6 "MyString"
    emotion "MyString"
    name_4 "MyString"
    picture "MyString"
  end
end
